//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargingPointTracker.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargePoint
    {
        public int Id { get; set; }
        public string ChargePointId { get; set; }
        public int LocationId { get; set; }
        public string FloorLevel { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string Status { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
